name: CML
on:
  push:
    branches: [ "model" ]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc pull
          python train.py  # generate plot.png
          dvc add modelo/model_pkl
          # Create CML report
          cat metrics.txt >> report.md
          echo '![](./confusion.png "Confusion Matrix")' >> report.md
          cml comment create report.md
           echo '![](./report.png "Report")' >> report.md
          cml comment create report.md
